json.id product.id
json.name product.name
json.price product.price
json.tax product.tax
json.total product.tax
json.is_discounted? product.is_discounted?
json.image_url product.image_url
json.description product.description
json.inventory product.inventory
json.supplier product.supplier